package com.kree.keehoo.leasegreendao2.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kree.keehoo.leasegreendao2.model.Person;
import com.kree.keehoo.leasegreendao2.model.Lease;

import com.kree.keehoo.leasegreendao2.model.PersonDao;
import com.kree.keehoo.leasegreendao2.model.LeaseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDaoConfig;
    private final DaoConfig leaseDaoConfig;

    private final PersonDao personDao;
    private final LeaseDao leaseDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        leaseDaoConfig = daoConfigMap.get(LeaseDao.class).clone();
        leaseDaoConfig.initIdentityScope(type);

        personDao = new PersonDao(personDaoConfig, this);
        leaseDao = new LeaseDao(leaseDaoConfig, this);

        registerDao(Person.class, personDao);
        registerDao(Lease.class, leaseDao);
    }
    
    public void clear() {
        personDaoConfig.getIdentityScope().clear();
        leaseDaoConfig.getIdentityScope().clear();
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

    public LeaseDao getLeaseDao() {
        return leaseDao;
    }

}
